import { JSX } from "react";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiDocker,
  SiReact,
  SiNextdotjs,
  SiHono,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiGnubash,
  SiGit,
  SiTailwindcss,
  SiDeno,
  SiNodedotjs,
  SiAxios,
  SiZod,
  SiNginx,
  SiGooglegemini,
  SiThreedotjs,
  SiVercel,
} from "react-icons/si";

export const techIcons: Record<string, JSX.Element> = {
  Javascript: <SiJavascript />,
  Typescript: <SiTypescript />,
  Python: <SiPython />,
  Docker: <SiDocker />,
  React: <SiReact />,
  Nextjs: <SiNextdotjs />,
  Vercel: <SiVercel />,
  TailwindCSS: <SiTailwindcss />,
  ThreeJS: <SiThreedotjs />,
  Deno: <SiDeno />,
  Nodejs: <SiNodedotjs />,
  Hono: <SiHono />,
  Express: <SiExpress />,
  Axios: <SiAxios />,
  Zod: <SiZod />,
  MongoDB: <SiMongodb />,
  Postgres: <SiPostgresql />,
  Redis: <SiRedis />,
  Bash: <SiGnubash />,
  Git: <SiGit />,
  Nginx: <SiNginx />,
  Gemini: <SiGooglegemini />,
};
